apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodesqswatcher
  name: nodesqswatcher-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodesqswatcher
  template:
    metadata:
      annotations:
        dapr.io/app-id: nodesqswatcher
        dapr.io/app-port: "8080"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
      labels:
        app: nodesqswatcher
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        image: harbor.freshbrewed.science/freshbrewedprivate/nodesqswatcher:1.13
        imagePullPolicy: Always
        name: nodesqswatcher
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: myharborreg
